ansible_user: ec2-user
ansible_ssh_private_key_file: ~/.ssh/clouddevops-key.pem
ansible_python_interpreter: /usr/bin/python3
ansible_connection: ssh
ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

