apiVersion: apps/v1
kind: Deployment
metadata:
  name: ivolve-deployment
  namespace: ivolve
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ivolve
  template:
    metadata:
      labels:
        app: ivolve
    spec:
      containers:
      - name: ivolve
        image: your-image:tag
        ports:
        - containerPort: 80

