apiVersion: v1
kind: Service
metadata:
  name: ivolve-service
  namespace: ivolve
spec:
  selector:
    app: ivolve
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

